apiVersion: v1
kind: Service
metadata:
  name: demo-flux-app
  namespace: demo-flux-app
spec:
  selector:
    app: demo-flux-app
  ports:
    - protocol: TCP
      port: 81
      targetPort: 80
  type: LoadBalancer